### ISSUE TITLE
Проектирование базовых эндпоинтов

### ISSUE THREAD

**Issue by codEnjoyer** [codEnjoyer/BeatBox-Booking-Backend#6]
CRUD над базовыми сущностями в парадигме JSON RPC, возможные ошибки, авторизация

**Comment by 2piCode** [comment]
JSON RPCCCCCC

**Comment by codEnjoyer** [comment]
> PC

cry about it

**Comment by dolbikcop** [comment]
https://docs.google.com/document/d/1_6TdbFstd5Cnv4hp_eCFuq5o39zWf8yhkE5GWGOSWNY/edit?usp=sharing
